---
title: "Evaluation of Latin NLP models"
author: "Petra Hermankova"
date: "21/01/2021"
output:
  html_document:
    theme: united
    toc: yes
    toc_float: true
    number_sections: true
    toc_depth: 2
    df_print: paged
---

# Initial setup

## Setup of the environment:

```{r setup, echo=TRUE, message=FALSE}
devtools::install_github("sdam-au/sdam") # loading SDAM custom package, if not working try 
# devtools::install_github("mplex/cedhar", subdir="pkg/sdam")
library(tidyverse)
library(sdam)
library(jsonlite)
library(tidytext)
```

## Loading data
1. Load the dataset, if you have Sciencedata.dk credentials

```{r, echo=FALSE}
mycred_secret<- readLines("~/mysecret.txt")
```

### Dataset 1
```{r, loading data}
resp = request("EDH_text_lemmatized_proiel_2021-01-21.json", path="/sharingin/648597@au.dk/SDAM_root/SDAM_data/EDH/public", method="GET", cred=mycred_secret)
```

2. Make a list and tibble from the request function
```{r}
list_json <- jsonlite::fromJSON(resp)
EDH_proiel <- as_tibble(list_json)
```

### Dataset 2
```{r, loading data}
resp = request("EDH_text_lemmatized_perseus_2021-01-21.json", path="/sharingin/648597@au.dk/SDAM_root/SDAM_data/EDH/public", method="GET", cred=mycred_secret)
```

2. Make a list and tibble from the request function
```{r}
list_json <- jsonlite::fromJSON(resp)
EDH_perseus <- as_tibble(list_json)
```

```{r, echo=FALSE}
remove(mycred_secret)
```

# Evaluation of results of two UDpipe NLP models for Latin


